# Generated by Django 4.1.6 on 2023-05-18 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок группы')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=500, verbose_name='Направление')),
                ('education', models.CharField(blank=True, max_length=500, verbose_name='Образование')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('experience', models.CharField(blank=True, max_length=500, verbose_name='Стаж')),
                ('place_education', models.TextField(blank=True, max_length=500, verbose_name='Место учёбы')),
                ('atchievments', models.TextField(blank=True, max_length=500, verbose_name='Достижения')),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.listgroups', verbose_name='Название группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информация о пользователях',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
    ]
