# Generated by Django 4.1.6 on 2023-05-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0003_listgroups_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250, verbose_name='Фио ребенка')),
                ('age', models.TextField(blank=True, max_length=5000, verbose_name='Возраст ребёнка')),
                ('birsday', models.DateField(verbose_name='Дата рождения ребёнка')),
                ('pol', models.CharField(choices=[('men', 'Мужской'), ('girl', 'Женский')], max_length=300, verbose_name='пол ребенка')),
                ('place_learning', models.CharField(max_length=250, verbose_name='Место обучения ребёнка')),
                ('sertificat_pfdo', models.PositiveIntegerField(max_length=250, verbose_name='Cертификат ПФДО рёбенка')),
                ('fio_parents', models.TextField(blank=True, max_length=500, verbose_name='ФИО родителей')),
                ('contact_data', models.PositiveIntegerField(max_length=250, verbose_name='Контактные данные')),
                ('atchievments', models.TextField(blank=True, max_length=500, verbose_name='Достижения')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список студентов',
                'verbose_name_plural': 'Список студентов',
            },
        ),
    ]
