# Generated by Django 4.1.6 on 2023-05-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_liststudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liststudents',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Возраст ребёнка'),
        ),
    ]
