# Generated by Django 4.1.6 on 2023-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_liststudents_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='liststudents',
            name='groups',
            field=models.ManyToManyField(to='firstapp.listgroups', verbose_name='Группы'),
        ),
    ]
