# Generated by Django 4.1.6 on 2023-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_liststudents_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liststudents',
            name='groups',
        ),
        migrations.AddField(
            model_name='listgroups',
            name='students',
            field=models.ManyToManyField(to='firstapp.liststudents', verbose_name='ученики группы'),
        ),
    ]
