# Generated by Django 4.1.6 on 2023-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_remove_liststudents_groups_listgroups_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listgroups',
            name='students',
        ),
        migrations.AddField(
            model_name='liststudents',
            name='groups',
            field=models.ManyToManyField(to='firstapp.listgroups', verbose_name='Группы'),
        ),
    ]
