# Generated by Django 4.1.6 on 2023-05-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_remove_listgroups_students_liststudents_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liststudents',
            name='pol',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=300, verbose_name='пол ребенка'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.listgroups', verbose_name='Название группы'),
        ),
    ]
