# Generated by Django 4.1.6 on 2023-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_liststudents_pol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, max_length=500, verbose_name='Стаж(в месяцах)'),
        ),
    ]
